### ISSUE TITLE
Only one operation can be active at a time

### ISSUE THREAD

**Issue by markobls** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#12]
**Using Xamarin.Forms on android.**

_{System.InvalidOperationException: Only one operation can be active at a time
  at Plugin.FilePicker.FilePickerImplementation.TakeMediaAsync (System.String type, System.String action) [0x00020] in C:\Plugin\FilePicker\FilePicker\FilePicker\Plugin.FilePicker.Android\FilePickerImplementation.cs:42 
  at Plugin.FilePicker.FilePickerImplementation+<PickFile>d__4.MoveNext () [0x0000a] in C:\Plugin\FilePicker\FilePicker\FilePicker\Plugin.FilePicker.Android\FilePickerImplementation.cs:31 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3819/96c7ba6c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357_ 

When i call CrossFilePicker.Current.PickFile() and do not select a file (pressing the hardwarebackbutton) and call CrossFilePicker.Current.PickFile() the following exception occurs:

**Using version 1.1.0**

What should I do ?

:/

**Comment by markobls** [comment]
Any help?

**Comment by JulianWreford** [comment]
@markobls Hi did you find a solution to this?

I also have a problem with this and other problem here: https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/issues/13

Thanks

**Comment by Naografix** [comment]
Same here. But I think, this project is down/finish.

**Comment by markobls** [comment]
yea..

sad

**Comment by jfversluis** [comment]
@markobls @JulianWreford @Naografix We are back! Did this ever get fixed?
Or could you create a simple repro project?

**Comment by ShahriatHossain** [comment]
@ jfversluis pressing hardware back button on android getting null tsc tas completion source and if I cancel to upload pdf on ios it is throwing me invalid operation, can these two bugs be fixed in a few days?

**Comment by jfversluis** [comment]
@ShahriatHossain I will try to have a look at it, but I can't guarantee anything. If you want to be sure you could try and fix it yourself and send us a PR.

**Comment by elmernocon** [comment]
any news on this?

**Comment by slam023** [comment]
Does this fully fixed. I still facing the same problem on one of my main project, even though it work on  newly created project.

**Comment by slam023** [comment]
Still having the problem in my project.
 
![3ftn0](https://cloud.githubusercontent.com/assets/16716114/23183321/85a851dc-f8e0-11e6-9620-9582fd6958d6.png)

I downloaded from nuget with version 1.1.0

**Comment by elmernocon** [comment]
@slam023 , Hi, any chance you're still using the NuGet package? because that one is heavily outdated. If you are, I suggest cloning this repo and rebuilding the .DLL(s). @jfversluis already posted the fix it's in  [iOS](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.iOS/FilePickerImplementation.cs) line 84 & 151. and for [android.FilePickerActivity.cs](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.Android/FilePickerActivity.cs) & [android.FilePickerImplementation.cs](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.Android/FilePickerImplementation.cs)

**Comment by slam023** [comment]
Yes I am using the nuget version. I do i tell what version the one in github

**Comment by slam023** [comment]
@elmernocon Yes you are right. The version in nuget is old. After adding this to my submodule from source tree and referenced to my project, the problem solved.

**Comment by jfversluis** [comment]
Sorry! I don't have the power to create NuGets so code here and what is on there is not in sync right now. Trying to work on it! Glad to see you worked it out!

**Comment by rahmanadianto** [comment]
@slam023 Hi, I'm new in xamarin form, how to add this kind of project in our project?

**Comment by santiagohdzb** [comment]
Why is this closed? NuGet package still gets this exception... :(

**Comment by jfversluis** [comment]
Active development moved here: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows

Please try the latest package there and open an issue if you run into anything

**Comment by dush88c** [comment]
This issue is still existing in 2.0.64-beta version. How can I get resolved this? Anyone got a solution. ?

**Comment by dush88c** [comment]
I used **1.4.0-beta** version which worked for me finally. Please **clean solution** and **build again** after the upgrade or downgrade the version.

**Comment by SsurajitBera** [comment]
@dush88c 
Thank You so much for your great experiencing help.
fixed it after so long time.

**Comment by jfversluis** [comment]
Please have another look at: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows we fixed the whole thing and active development is ongoing there
